name: Cypress CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  IMAGE_NAME: ghcr.io/thanhtrungtran-testautomation/portfolio-cypress/app  

jobs:
  # -----------------------------
  # BUILD DOCKER IMAGE
  # -----------------------------
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v6
         
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          docker build \
          --cache-from=${IMAGE_NAME}:latest \
          -t ${IMAGE_NAME}:${{ github.sha }} \
          -t ${IMAGE_NAME}:latest .

      - name: Push image
        run: |
          docker push ${IMAGE_NAME}:${{ github.sha }}
    
  # -----------------------------
  # CYPRESS TESTS
  # -----------------------------
  cypress-serial:
      needs: build-image
      runs-on: ubuntu-latest
      container:
        image: ghcr.io/thanhtrungtran-testautomation/portfolio-cypress/app:${{ github.sha }}
      steps:
      - uses: actions/checkout@v6

      #- name: Pull image
      #  run: |         
      #    docker pull ${IMAGE_NAME}:${{ github.sha }}

      #- name: Start container
      #  run: |       
      #    docker run -d -p 3000:3000 ${IMAGE_NAME}:${{ github.sha }}   
      
      - name: Clean old test reports
        run: rm -f results/junit.xml          
            
      - name: Install dependencies
        run: npm ci

      # Demo-App starten und Cypress Tests ausführen      
      - name: Run Cypress
        run: npx start-server-and-test "npm start" http://localhost:3000 "npx cypress run --browser chrome --headless"
                     
      - name: Rename JUnit files
        run: |
          for file in results/junit-*.xml; do
          # Extract the spec filename from the <testsuite file="..."> attribute
          SPEC_NAME=$(grep -oP '(?<=file=")[^"]+' "$file" | head -1)
          # Entferne Pfad und Dateiendung
          SPEC_NAME=$(basename "$SPEC_NAME" .cy.js)
          # Datei umbenennen
          mv "$file" "results/junit-$SPEC_NAME.xml"
          done
      
      - name: Merge Mochawesome reports
        if: always()
        run: |
          npx mochawesome-merge results/*.json -o results/report.json
          npx mochawesome-report-generator results/report.json \
          --reportDir results \
          --reportFilename report \
          --inline      
      
        # Artefakte hochladen
      - name: Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            results
            cypress/videos
            cypress/screenshots  
    
  cypress-queue-create:
    runs-on: ubuntu-latest

    outputs:
      specs: ${{ steps.specs.outputs.specs }}

    steps:
      - uses: actions/checkout@v6

      - name: Create test queue
        id: specs
        run: |
          ls cypress/e2e/*.cy.js > spec-queue.txt
          cat spec-queue.txt

      - uses: actions/upload-artifact@v4
        with:
          name: spec-queue
          path: spec-queue.txt
  
  cypress-parallel-dynamic-queue-pull:
    needs: 
      - build-image
      - cypress-queue-create
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/thanhtrungtran-testautomation/portfolio-cypress/app:${{ github.sha }}
    strategy:
      fail-fast: false
      matrix:
        runner: [1,2]

    steps:
    - uses: actions/checkout@v6

    - uses: actions/download-artifact@v4
      with:
          name: spec-queue      

    - name: Start App      
      run: |        
        npm ci
        npm install cypress-split --save-dev                
        npm install        
        npm start &   # App im Hintergrund
        npx wait-on http://localhost:3000    
    
    - name: Debug env
      run: |
        echo "machine=${{ matrix.runner }}"
    
    - name: Debug specs
      run: ls -R cypress

    - name: Run tests dynamically
      run: |
        while true
        do
          SPEC=$(head -n 1 spec-queue.txt)
          if [ -z "$SPEC" ]; then
            echo "Queue empty"
            break
          fi

          sed -i '1d' spec-queue.txt
          echo "Running $SPEC"
          npx cypress run \
            --spec "$SPEC" \
            --browser chrome \
            --headless
        done  

  cypress-specs-find:    
    runs-on: ubuntu-latest

    outputs:
      specs: ${{ steps.specs.outputs.specs }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find Cypress specs
        id: specs
        run: |
          SPECS=$(ls cypress/e2e/*.cy.js | sort -r | jq -R -s -c 'split("\n")[:-1]')
          echo "specs=$SPECS" >> $GITHUB_OUTPUT
          echo "Detected and sorted specs: $SPECS"
  
  cypress-parallel-per-spec:
    needs: 
      - cypress-specs-find
      - build-image
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/thanhtrungtran-testautomation/portfolio-cypress/app:${{ github.sha }}
    strategy:
      fail-fast: false
      matrix:
        spec: ${{ fromJson(needs.cypress-specs-find.outputs.specs) }}
        
    steps:
    - uses: actions/checkout@v4    

    - name: Clean old test reports
      run: rm -f results/junit.xml 
    
    - name: Start App
      
      run: |        
        npm ci                
        npm install        
        npm start &   # App im Hintergrund
        npx wait-on http://localhost:3000    
    
    - name: Debug env
      run: |
        echo "machine=${{ matrix.spec }}"
    
    - name: Debug specs
      run: ls -R cypress
    
    - name: Run Cypress tests
      run: |
        echo "Running spec: ${{ matrix.spec }}"  
        npx cypress run \
        --browser chrome \
        --headless \
        --spec "${{ matrix.spec }}"  \
            --reporter mochawesome \
            --reporter-options reportDir=results,overwrite=false,html=false,json=true
    
    - name: Extract spec name
      id: specname
      run: |
        SPEC_FILE=$(basename "${{ matrix.spec }}")
        echo "name=$SPEC_FILE" >> $GITHUB_OUTPUT
    
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: results-${{ steps.specname.outputs.name }}
        path:  |
          results
          cypress/videos
          cypress/screenshots

# ------------------------------------------------
# MERGE TEST REPORTS
# ------------------------------------------------
  merge-reports:
    needs: cypress-parallel-per-spec
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/thanhtrungtran-testautomation/portfolio-cypress/app:${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: reports

      - name: Install report tools
        run: |
          npm install mochawesome mochawesome-merge mochawesome-report-generator

      - name: Merge reports
        run: |
          node node_modules/mochawesome-merge/bin/mochawesome-merge.js reports/**/results/*.json > merged-report.json

      - name: Generate HTML report
        run: |
          node node_modules/mochawesome-report-generator/bin/marge.js merged-report.json \
          --reportDir final-report \
          --reportFilename index \
          --inline

      - name: Upload final report
        uses: actions/upload-artifact@v4
        with:
          name: final-report
          path: final-report

# ------------------------------------------------
# DEPLOY REPORT TO GITHUB PAGES
# ------------------------------------------------
  deploy-report:
    needs: merge-reports
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Download final report
        uses: actions/download-artifact@v4
        with:
          name: final-report
          path: site

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4      

  cypress-parallel-static-runner:
    needs: build-image
    runs-on: ubuntu-latest  
    container:
      image: ghcr.io/thanhtrungtran-testautomation/portfolio-cypress/app:${{ github.sha }}
    strategy:
      fail-fast: false
      matrix:
        machine: [0,1]

    steps:
    - uses: actions/checkout@v4    
    
    - name: Install dependencies
      run: npm ci

    - name: Start demo app
      run: |
        npm start &
        npx wait-on http://localhost:3000

    - name: Run Cypress
      run: |
        if [ "${{ matrix.machine }}" = "0" ]; then
          npx cypress run --spec "cypress/e2e/Login_test.cy.js,cypress/e2e/Dashboard_test.cy.js"
        elif [ "${{ matrix.machine }}" = "1" ]; then
          npx cypress run --spec "cypress/e2e/Form_test.cy.js,cypress/e2e/Utils_test.cy.js"        
        fi          
# ------------------------------------------------
# CYPRESS TEST IN KUBERNETES
# ------------------------------------------------
  cypress-kubernetes-cluster:
    needs: build-image    
    runs-on: ubuntu-latest
    #container:
    #  image: bitnami/kubectl:latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.30.0'

      - name: Setup kind
        uses: engineerd/setup-kind@v0.6.2
        with:
          version: "v0.24.0"

      - name: Create kind cluster
        run: |
          kind create cluster --name cypress --wait 5m

      - name: Create namespace
        run: |
          kubectl create namespace cypress-e2e --dry-run=client -o yaml | kubectl apply -f -
          
      - name: Pull image from GHCR
        run: |
          docker pull ${IMAGE_NAME}:${{ github.sha }}

      - name: Check local images
        run: docker images
      
      - name: Load built image into kind
        run: |
          kind load docker-image ${IMAGE_NAME}:${{ github.sha }} --name cypress

      - name: Check cluster
        run: |
          kubectl cluster-info
          kubectl get nodes

      #- name: Setup kubeconfig
      #  run: |
      #    echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
      #    export KUBECONFIG=$PWD/kubeconfig >> $GITHUB_ENV
      #    kubectl config view --kubeconfig=kubeconfig

      #- name: Test cluster connection
      #  run: KUBECONFIG=$PWD/kubeconfig kubectl get nodes

      - name: Run Cypress job in cluster      
        run: |
          sed "s|IMAGE_TAG|${{ github.sha }}|g" k8s/cypress-github-job.yml | kubectl apply -f -

      - name: Debug cluster
        run: |
          kubectl get jobs -A
          kubectl get pods -n cypress-e2e
          kubectl get pods -A

      - name: Debug jobs
        run: kubectl get jobs -n cypress-e2e

      - name: Describe pod
        run: |
          kubectl describe pod -n cypress-e2e

      - name: Wait for Job
        run: |
          kubectl wait \
          --for=condition=complete \
          job/cypress-run \
          --namespace cypress-e2e \
          --timeout=600s

      - name: Show pod logs
        run: |
          kubectl logs -n cypress-e2e -l job-name=cypress-run

  # -----------------------------
# MERGE REPORTS Cypress in Cluster
# -----------------------------
  merge-reports-cluster:
    needs: cypress-kubernetes-cluster
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: reports

      - name: Install report tools
        run: |
          npm install mochawesome mochawesome-merge mochawesome-report-generator

      - name: Merge reports
        run: |
          npx mochawesome-merge reports/**/*.json > report.json
      - name: Generate HTML
        run: |
          npx mochawesome-report-generator report.json \
            --reportDir site \
            --reportFilename index \
            --inline

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

  # -----------------------------
# DEPLOY REPORT TO GITHUB PAGES
# -----------------------------
  deploy-report-cluster:
    needs: merge-reports-cluster
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/deploy-pages@v4