name: Cypress CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/thanhtrungtran-testautomation/portfolio-cypress/app
  RUN_CYPRESS_CLUSTER: "true"

jobs:
  # -----------------------------
  # BUILD DOCKER IMAGE
  # -----------------------------
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Convert image name to lowercase
        id: vars
        run: |
          IMAGE=$(echo "${IMAGE_NAME}" | tr '[:upper:]' '[:lower:]')
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
      
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          docker build \
          --cache-from=${{ steps.vars.outputs.image }}:latest \
          -t ${{ steps.vars.outputs.image }}:${{ github.sha }} \
          -t ${{ steps.vars.outputs.image }}:latest .

      - name: Push image
        run: |
          docker push ${{ steps.vars.outputs.image }}:${{ github.sha }}
    
  # -----------------------------
  # CYPRESS TESTS
  # -----------------------------
  cypress-run:
    needs: build-image
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/thanhtrungtran-testautomation/portfolio-cypress/app:${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      #- name: Pull image
      #  run: |
      #    IMAGE=$(echo "${IMAGE_NAME}" | tr '[:upper:]' '[:lower:]')
      #    docker pull $IMAGE:{{ github.sha }}

      # Demo-App starten und Cypress Tests ausführen      
      #- name: Run Cypress
      #  run: npx start-server-and-test "npm start" http://localhost:3000 "npx cypress run --browser chrome --headless"
      
      - name: Clean old test reports
        run: rm -f results/junit.xml
      
      #- name: Start container
      #  run: |
      #    IMAGE=$(echo "${IMAGE_NAME}" | tr '[:upper:]' '[:lower:]')  
      #    docker run -d -p 3000:3000 $IMAGE:{{ github.sha }}

      #- name: Test endpoint 3000
      #  run: curl -v http://localhost:3000

      #- name: Test endpoint 8080
      #  run: curl -v http://localhost:8080
      
      #- name: Fix permissions
      #  run: chmod +x node_modules/.bin/*
      
      - name: Install dependencies
        run: npm ci
      
      - name: Start App
        run: |
          npm start &   # App im Hintergrund
          npx wait-on http://localhost:3000 -t 60000

      - name: Run Cypress Tests
        run: npx cypress run --browser chrome --headless        
         
      - name: Rename JUnit files
        run: |
          for file in results/junit-*.xml; do
          # Extract the spec filename from the <testsuite file="..."> attribute
          SPEC_NAME=$(grep -oP '(?<=file=")[^"]+' "$file" | head -1)
          # Entferne Pfad und Dateiendung
          SPEC_NAME=$(basename "$SPEC_NAME" .cy.js)
          # Datei umbenennen
          mv "$file" "results/junit-$SPEC_NAME.xml"
          done
      
      - name: Merge Mochawesome reports
        if: always()
        run: |
          npx mochawesome-merge results/*.json -o results/report.json
          npx mochawesome-report-generator results/report.json \
          --reportDir results \
          --reportFilename report \
          --inline      
      
        # Artefakte hochladen
      - name: Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            results
            cypress/videos
            cypress/screenshots

  cypress-parallel:
    needs: build-image
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        machine: [0,1]

    steps:
    - uses: actions/checkout@v4

    - name: Pull image
      run: |
        IMAGE=$(echo "${IMAGE_NAME}" | tr '[:upper:]' '[:lower:]')
        docker pull $IMAGE:${{ github.sha }}

    - name: Start container
      run: |
        IMAGE=$(echo "${IMAGE_NAME}" | tr '[:upper:]' '[:lower:]')  
        docker run -p 3000:3000 $IMAGE:${{ github.sha }}

    - name: Start App
      
      run: |        
        npm ci          
        npm start &   # App im Hintergrund
        npx wait-on http://localhost:3000

    - name: Debug split
      run: |
        echo "splitIndex = ${{ matrix.machine }}"
        echo "splitTotal = 2"
    
    - name: Run Cypress parallel
      run: |
        npx cypress run \
        --browser chrome --headless \
        --env split=true,splitIndex=${{ matrix.machine }},splitTotal=2

  # ------------------------------------------------
# CYPRESS TEST IN KUBERNETES
# ------------------------------------------------
#  cypress-cluster:
 #   needs: build-image
  #  
   # runs-on: ubuntu-latest

    #container:
     # image: bitnami/kubectl:latest

    #steps:
     # - uses: actions/checkout@v4

      #- name: Setup kubeconfig
       # run: |
        #  echo "{{ secrets.KUBE_CONFIG }}" > kubeconfig
         # export KUBECONFIG=$PWD/kubeconfig >> $GITHUB_ENV

     # - name: Test cluster connection
      #  run: KUBECONFIG=$PWD/kubeconfig kubectl get nodes

      #- name: Run Cypress job in cluster
       # run: |
        #  kubectl apply -f k8s/cypress-job2.yml