name: Cypress CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # -----------------------------
  # BUILD DOCKER IMAGE
  # -----------------------------
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/app:${{ github.sha }} .

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository }}/app:${{ github.sha }}
    
  # -----------------------------
  # CYPRESS TESTS
  # -----------------------------
  cypress-run:
    needs: build-image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Pull image
        run: |
          docker pull ghcr.io/${{ github.repository }}/app:${{ github.sha }}

      # Demo-App starten und Cypress Tests ausführen      
      #- name: Run Cypress
      #  run: npx start-server-and-test "npm start" http://localhost:3000 "npx cypress run --browser chrome --headless"
      
      - name: Clean old test reports
        run: rm -f results/junit.xml
      
      - name: Start container
        run: |
          docker run -d -p 3000:3000 ghcr.io/${{ github.repository }}/app:${{ github.sha }}
      
      - name: Start App
        run: |
          npm start &
          npx wait-on http://localhost:3000

      - name: Run Cypress Tests
        run: npx cypress run --browser chrome --headless        
         
      - name: Rename JUnit files
        run: |
          for file in results/junit-*.xml; do
          # Extract the spec filename from the <testsuite file="..."> attribute
          SPEC_NAME=$(grep -oP '(?<=file=")[^"]+' "$file" | head -1)
          # Entferne Pfad und Dateiendung
          SPEC_NAME=$(basename "$SPEC_NAME" .cy.js)
          # Datei umbenennen
          mv "$file" "results/junit-$SPEC_NAME.xml"
          done
      
      - name: Merge Mochawesome reports
        if: always()
        run: |
          npx mochawesome-merge results/*.json -o results/report.json
          npx mochawesome-report-generator results/report.json \
          --reportDir results \
          --reportFilename report \
          --inline      
      
        # Artefakte hochladen
      - name: Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            results
            cypress/videos
            cypress/screenshots

  cypress-parallel:
    needs: build-image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container: [1,2,3]

    steps:
    - uses: actions/checkout@v4

    - name: Pull image
      run: docker pull ghcr.io/${{ github.repository }}/app:${{ github.sha }}

    - name: Start container
      run: docker run -d -p 3000:3000 ghcr.io/${{ github.repository }}/app:${{ github.sha }}

    - name: Start App
      run: |
          npm start &
          npx wait-on http://localhost:3000

    - name: Run Cypress parallel
      run: |
        npx cypress run \
        --record \
        --parallel